apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'offers'
        static_configs:
          - targets: ['offers-service.default.svc.cluster.local:5000']
      - job_name: 'auth'
        static_configs:
          - targets: ['auth-service.default.svc.cluster.local:5001']
      - job_name: 'contact'
        static_configs:
          - targets: ['contact-service.default.svc.cluster.local:5002']
