apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: globalnet
      service: contact
  template:
    metadata:
      labels:
        app: globalnet
        service: contact
    spec:
      containers:
        - name: contact
          image: yasminech123/contact-service:latest
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: contact-service
  labels:
    app: globalnet
    service: contact
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: globalnet
    service: contact
  ports:
    - name: http
      port: 5002
      targetPort: 5002
