apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globalnet-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: globalnet.local
    http:
      paths:
      - path: /offers
        pathType: Prefix
        backend:
          service:
            name: offers-service
            port:
              number: 80
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /contact
        pathType: Prefix
        backend:
          service:
            name: contact-service
            port:
              number: 80
