apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: globalnet
      service: offers
  template:
    metadata:
      labels:
        app: globalnet
        service: offers
    spec:
      containers:
        - name: offers
          image: yasminech123/offers-service:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: offers-service
  labels:
    app: globalnet
    service: offers
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: globalnet
    service: offers
  ports:
    - name: http
      port: 5000
      targetPort: 5000
