apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
      - name: offers
        image: yasminech123/offers-service:latest
        ports:
        - containerPort: 5000
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: offers-service
spec:
  selector:
    app: offers
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
