apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: yasminech123/web-ui:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
spec:
  type: NodePort
  selector:
    app: web-ui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30010
